<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAw1dauh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAw1dauh/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAw1dauh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAw1dauh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAw1dauh\appProdProjectContainer([
    'container.build_hash' => 'Aw1dauh',
    'container.build_id' => '25b0bc77',
    'container.build_time' => 1775728300,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAw1dauh');
