<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PrestashopCheckout\PayPal\ApplePay\Builder\ApplePayPaymentRequestBuilder' shared service.

return $this->services['PrestaShop\\Module\\PrestashopCheckout\\PayPal\\ApplePay\\Builder\\ApplePayPaymentRequestBuilder'] = new \PrestaShop\Module\PrestashopCheckout\PayPal\ApplePay\Builder\ApplePayPaymentRequestBuilder(${($_ = isset($this->services['PrestaShop\\Module\\PrestashopCheckout\\Translations\\Translations']) ? $this->services['PrestaShop\\Module\\PrestashopCheckout\\Translations\\Translations'] : $this->load('getTranslationsService.php')) && false ?: '_'});
