<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PrestashopCheckout\Logger\LoggerFileReader' shared service.

return $this->services['PrestaShop\\Module\\PrestashopCheckout\\Logger\\LoggerFileReader'] = new \PrestaShop\Module\PrestashopCheckout\Logger\LoggerFileReader(${($_ = isset($this->services['PrestaShop\\Module\\PrestashopCheckout\\Logger\\LoggerDirectory']) ? $this->services['PrestaShop\\Module\\PrestashopCheckout\\Logger\\LoggerDirectory'] : ($this->services['PrestaShop\\Module\\PrestashopCheckout\\Logger\\LoggerDirectory'] = new \PrestaShop\Module\PrestashopCheckout\Logger\LoggerDirectory('1.7.6.1', $this->targetDirs[3]))) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PrestashopCheckout\\Logger\\LoggerFileFinder']) ? $this->services['PrestaShop\\Module\\PrestashopCheckout\\Logger\\LoggerFileFinder'] : $this->load('getLoggerFileFinderService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PrestashopCheckout\\Adapter\\ValidateAdapter']) ? $this->services['PrestaShop\\Module\\PrestashopCheckout\\Adapter\\ValidateAdapter'] : ($this->services['PrestaShop\\Module\\PrestashopCheckout\\Adapter\\ValidateAdapter'] = new \PrestaShop\Module\PrestashopCheckout\Adapter\ValidateAdapter())) && false ?: '_'});
