<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PrestashopCheckout\PayPal\OAuth\OAuthService' shared service.

return $this->services['PrestaShop\\Module\\PrestashopCheckout\\PayPal\\OAuth\\OAuthService'] = new \PrestaShop\Module\PrestashopCheckout\PayPal\OAuth\OAuthService(${($_ = isset($this->services['PrestaShop\\Module\\PrestashopCheckout\\Http\\CheckoutHttpClient']) ? $this->services['PrestaShop\\Module\\PrestashopCheckout\\Http\\CheckoutHttpClient'] : $this->load('getCheckoutHttpClientService.php')) && false ?: '_'});
