<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PrestashopCheckout\ShopContext' shared service.

return $this->services['PrestaShop\\Module\\PrestashopCheckout\\ShopContext'] = new \PrestaShop\Module\PrestashopCheckout\ShopContext(${($_ = isset($this->services['PrestaShop\\Module\\PrestashopCheckout\\Environment\\Env']) ? $this->services['PrestaShop\\Module\\PrestashopCheckout\\Environment\\Env'] : $this->load('getEnvService.php')) && false ?: '_'});
