<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKxlms8s\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKxlms8s/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKxlms8s.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKxlms8s\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKxlms8s\appDevDebugProjectContainer([
    'container.build_hash' => 'Kxlms8s',
    'container.build_id' => '96ce7a82',
    'container.build_time' => 1775728845,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKxlms8s');
