<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PrestashopCheckout\Logger\LoggerFileFinder' shared service.

return $this->services['PrestaShop\\Module\\PrestashopCheckout\\Logger\\LoggerFileFinder'] = new \PrestaShop\Module\PrestashopCheckout\Logger\LoggerFileFinder(${($_ = isset($this->services['PrestaShop\\Module\\PrestashopCheckout\\Logger\\LoggerDirectory']) ? $this->services['PrestaShop\\Module\\PrestashopCheckout\\Logger\\LoggerDirectory'] : ($this->services['PrestaShop\\Module\\PrestashopCheckout\\Logger\\LoggerDirectory'] = new \PrestaShop\Module\PrestashopCheckout\Logger\LoggerDirectory('1.7.6.1', $this->targetDirs[3]))) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PrestashopCheckout\\Logger\\LoggerFilename']) ? $this->services['PrestaShop\\Module\\PrestashopCheckout\\Logger\\LoggerFilename'] : $this->load('getLoggerFilenameService.php')) && false ?: '_'});
